In [2]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# Shape of the array is 4x4, then we write the shape in (4,4)
arr = np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
type(arr)

numpy.ndarray

In [13]:
arr = arr.reshape(8,2)

In [14]:
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
arr.shape

(8, 2)

# Loops: 
#### In programming, loops are set of instructions that are repeated over and over again until certain condition is met.
1. The popular loops in Python are For-Loop and While-Loop
2. We have condition for loops, and we have body of loop
3. The if condition-of-loop is TRUE (remember Boolean Algebra), the body of loop will execute.

In [16]:
arr_2 = np.array([0,2,4,8,16,32,64,128])

for i in arr_2:
    print(i) 

0
2
4
8
16
32
64
128


In [20]:
# Press button 'b' to insert new cell below

for i in range(5):
    print(i*3)

0
The body of loop does not exist
3
The body of loop does not exist
6
The body of loop does not exist
9
The body of loop does not exist
12
The body of loop does not exist


# Control Statements: 
#### In programming, control statements allow the change in flow of the program.
1. Usually, in Python programming, statements follow a sequence.
2. The control statement enable to break that flow based on certain conditions.
3. if-else commands are a popular example of control statement. 
4. if-else works this way: If certain condition(s) are TRUE, then perform a certain task, if that condition is FALSE then do another task

   if condition is TRUE:
      DO THIS TASK (set of instructions).
   else:
      DO THIS TASK (set of instructions).

In [21]:
# Find if the number is an EVEN or ODD number

num = 40

if num%2 == 0:
    print('This is an EVEN number')
else:
    print('This is an ODD number')


This is an EVEN number


In [22]:
# Count postive, negative numbers, and zeros. Also print the smallest and largest number

import numpy as np

# A list of number 

num = [10, -30, 40, 0, 100, -9, 8, 5, 6, -60, 50, 80, 7, 0, 8, -34, 0]

positive_cnt = 0
negative_cnt = 0
zero_cnt = 0

smallest_num = np.inf # postivie infinity
largest_number = -np.inf

for i in num:
    
    # Counting numbers
    if i == 0:
        zero_cnt +=1 # zero_cnt = zero_cnt + 1 
    elif i < 0 :
        negative_cnt +=1
    else:
        positive_cnt +=1
        
    # Finding greater and smaller numbers
    if i < smallest_num: 
        smallest_num = i
    
    if i > largest_number: 
        largest_number = i 

print('Total number of Zeros are : ', zero_cnt)
print('Total number of negative numbers are : ', negative_cnt)
print('Total number of positive numbers are : ', positive_cnt)
print('------------------------------------------------------')
print('------------------------------------------------------')
print('The smallest number in the LIST is ', smallest_num, 'and the largest number is ', largest_number)

Total number of Zeros are :  3
Total number of negative numbers are :  4
Total number of positive numbers are :  10
------------------------------------------------------
------------------------------------------------------
The smallest number in the LIST is  -60 and the largest number is  100


In [28]:
cnt = 1

while(1): 
    print('cnt = {}'.format(cnt))
    cnt+=2 # cnt = cnt + 2
    
    if (cnt > 10):
        break

cnt = 1
cnt = 3
cnt = 5
cnt = 7
cnt = 9
